added aphrodite engine

diff --git a/templates/aphrodite/template.yaml b/templates/aphrodite/template.yaml
--- a/templates/aphrodite/template.yaml
+++ b/templates/aphrodite/template.yaml
@@ -6,8 +6,7 @@ metadata:
     # must have this label
     kalavai.job.name: {{deployment_id}}
 spec:
-  queue: {{queue_name}}
-  #minAvailable: 2
+  queue: default
   schedulerName: volcano
   plugins:
     env: []
@@ -15,9 +14,11 @@ spec:
   policies: 
   - event: PodEvicted # Restart the job when a pod is evicted.
     action: RestartJob
+  - event: TaskCompleted
+    action: CompleteJob
   tasks:
   - replicas: 1   # One ps pod specified
-    name: ps
+    name: server
     template: # Definition of the ps pod
       metadata:
         annotations:
@@ -30,31 +31,31 @@ spec:
       spec:
         runtimeClassName: nvidia
         containers:
-        - command:
+        - name: aphrodite-leader
+          image: docker.io/bundenth/ray-aphrodite:latest
+          command:
           - sh
           - -c
           - |
-            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh leader --ray_cluster_size=$(({{workers}})) --ray_port=6379 --ray_object_store_memory={{shmem_size * 1000000000}};
+            # Check if model is already on s3 or download
+            /home/ray/workspace/download_model.sh \
+              --model_id={{model_id}} \
+              --remote_dir="/home/ray/cache";
+            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh leader --ray_cluster_size=$(({{workers}})) --ray_object_store_memory={{memory * 500000000}};
             sleep 30;
             nvidia-smi;
             ray status;
+            # Run model
             /home/ray/workspace/run_model.sh \
-              --repo_id={{repo_id}} \
-              --model_filename={{model_filename}} \
+              --model_id="{{model_id}}" \
+              --model_path="/home/ray/cache/{{model_id}}" \
               --extra='{{extra}}' \
               --tensor_parallel_size={{tensor_parallel_size}} \
-              --pipeline_parallel_size={{pipeline_parallel_size}} \
-              --local_dir=/home/ray/cache;
-            sleep 30
-          image: docker.io/bundenth/ray-aphrodite:latest  #v1.0.11
-          name: aphrodite
+              --pipeline_parallel_size={{pipeline_parallel_size}}
+            exit 1
           env:
           - name: HF_TOKEN
             value: {{hf_token}}
-          - name: HF_HOME
-            value: /home/ray/cache
-          - name: TMPDIR
-            value: /home/ray/cache/tmp
           ports:
           - containerPort: 8080
             name: model-port
@@ -71,18 +72,88 @@ spec:
               nvidia.com/gpu: {{gpus}}
           volumeMounts:
             - mountPath: /dev/shm
-              name: dshm   
+              name: dshm
             - name: cache
               mountPath: /home/ray/cache
         volumes:
         - name: dshm
           emptyDir:
             medium: Memory
-            sizeLimit: {{shmem_size}}Gi
+            sizeLimit: {{memory * 0.5}}Gi
         - name: cache
           persistentVolumeClaim:
             claimName: {{storage}}
-        restartPolicy: Never
+        restartPolicy: OnFailure
+  - replicas: 1   # One ps pod specified
+    name: registrar
+    template: # Definition of the ps pod
+      terminationGracePeriodSeconds: 30 #give enough time to the preStop hook
+      metadata:
+        labels:
+          kalavai.job.name: {{deployment_id}}
+      spec:
+        containers:
+        - name: aphrodite-registrar
+          image: docker.io/bundenth/kalavai-utils:latest
+          env:
+          - name: VC_NAMESPACE
+            valueFrom:
+              fieldRef:
+                fieldPath: metadata.namespace
+          command:
+          - sh
+          - -c
+          - |
+            if [ ! -z "{{litellm_base_url}}" ]; then
+              echo $VC_NAMESPACE;
+              # wait for model to be served
+              echo "Waiting for model service..."
+              PS_HOST=`cat /etc/volcano/server.host`;
+              /workspace/wait_for_service.sh --servers="$PS_HOST" --port=8080
+              # Register model with LiteLLM
+              PS_HOST=`cat /etc/volcano/server.host`;
+              LITELLM_MODEL_NAME={{deployment_id}};
+              echo "Creating new entry on LiteLLM: (host: $PS_HOST) - (model id: $LITELLM_MODEL_NAME)";
+              API_BASE="http://"$PS_HOST"."$VC_NAMESPACE":8080/v1";
+              /workspace/register_model.sh \
+                --litellm_base_url={{litellm_base_url}} \
+                --litellm_key={{litellm_key}} \
+                --litellm_model_name="$LITELLM_MODEL_NAME" \
+                --model_id={{model_id}} \
+                --provider=hosted_vllm \
+                --api_base=$API_BASE \
+                --model_info='{"extra": "{{extra}}", "cpus": "{{cpus}}", "gpus": "{{gpus}}", "memory": "{{memory}}", "tensor_parallel_size": "{{tensor_parallel_size}}", "pipeline_parallel_size": "{{pipeline_parallel_size}}"}'
+            else
+              echo "[Warning] Missing LiteLLM base url. Model not publicly registered"
+              tail -f /dev/null
+            fi
+          lifecycle:
+            preStop:
+              exec:
+                command: 
+                - sh
+                - -c
+                - |       
+                  if [ ! -z "{{litellm_base_url}}" ]; then
+                    LITELLM_MODEL_NAME={{deployment_id}};       
+                    MODEL_ID=$(python3 /workspace/get_litellm_id.py \
+                      --litellm_url={{litellm_base_url}} \
+                      --api_key={{litellm_key}} \
+                      --model_name="$LITELLM_MODEL_NAME");
+                    curl -X POST "{{litellm_base_url}}/model/delete" \
+                        -H 'Authorization: Bearer {{litellm_key}}' \
+                        -H "accept: application/json" \
+                        -H "Content-Type: application/json" \
+                        -d '{ "id": "'$MODEL_ID'"}';
+                  fi
+          resources:
+            requests:
+              cpu: 0.1
+              memory: 0.1Gi
+            limits:
+              cpu: 0.1
+              memory: 0.1Gi
+        restartPolicy: OnFailure
   - replicas: {{workers - 1}}
     name: worker
     policies:
@@ -99,23 +170,18 @@ spec:
       spec:
         runtimeClassName: nvidia
         containers:
-        - command:
+        - name: aphrodite-worker
+          image: docker.io/bundenth/ray-aphrodite:latest
+          command:
           - sh
           - -c
           - |
             PS_HOST=`head /etc/volcano/ps.host`;
-            WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
             nvidia-smi;
-            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh worker --ray_address=$PS_HOST --ray_port=6379 --ray_object_store_memory={{ * 1000000000}} --ray_block=1
-          image: docker.io/bundenth/ray-aphrodite:latest  #v1.0.11
+            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh worker --ray_address=$PS_HOST --ray_port=6379 --ray_object_store_memory={{memory * 500000000}} --ray_block=1
           env:
           - name: HF_TOKEN
             value: {{hf_token}}
-          - name: HF_HOME
-            value: /home/ray/cache
-          - name: TMPDIR
-            value: /home/ray/cache/tmp
-          name: aphrodite
           resources:
             requests:
               cpu: {{cpus}}
@@ -128,9 +194,14 @@ spec:
           volumeMounts:
             - mountPath: /dev/shm
               name: dshm
+            - name: cache
+              mountPath: /home/ray/cache
         volumes:
         - name: dshm
           emptyDir:
             medium: Memory
-            sizeLimit: {{shmem_size}}Gi
-        restartPolicy: Never
+            sizeLimit: {{memory * 0.5}}Gi
+        - name: cache
+          persistentVolumeClaim:
+            claimName: {{storage}}
+        restartPolicy: OnFailure
