deactivate pypi to test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -101,121 +101,121 @@ jobs:
             ${{ steps.secrets.outputs.DOCKER_SECRETS }}
 ---
 
-  publish-to-pypi:
-    name: >-
-      Publish Python 🐍 distribution 📦 to PyPI
-    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
-    needs:
-    - build
-    runs-on: ubuntu-24.04
-    environment:
-      name: pypi
-      url: https://pypi.org/p/kalavai-client
-    permissions:
-      id-token: write  # IMPORTANT: mandatory for trusted publishing
+#   publish-to-pypi:
+#     name: >-
+#       Publish Python 🐍 distribution 📦 to PyPI
+#     if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
+#     needs:
+#     - build
+#     runs-on: ubuntu-24.04
+#     environment:
+#       name: pypi
+#       url: https://pypi.org/p/kalavai-client
+#     permissions:
+#       id-token: write  # IMPORTANT: mandatory for trusted publishing
 
-    steps:
-    - name: Download all the dists
-      uses: actions/download-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
-    - name: Publish distribution 📦 to PyPI
-      uses: pypa/gh-action-pypi-publish@release/v1
+#     steps:
+#     - name: Download all the dists
+#       uses: actions/download-artifact@v4
+#       with:
+#         name: python-package-distributions
+#         path: dist/
+#     - name: Publish distribution 📦 to PyPI
+#       uses: pypa/gh-action-pypi-publish@release/v1
 
----
+# ---
 
-  publish-to-testpypi:
-    name: Publish Python 🐍 distribution 📦 to TestPyPI
-    needs:
-    - build
-    runs-on: ubuntu-24.04
+#   publish-to-testpypi:
+#     name: Publish Python 🐍 distribution 📦 to TestPyPI
+#     needs:
+#     - build
+#     runs-on: ubuntu-24.04
 
-    environment:
-      name: testpypi
-      url: https://test.pypi.org/p/kalavai-client
+#     environment:
+#       name: testpypi
+#       url: https://test.pypi.org/p/kalavai-client
 
-    permissions:
-      id-token: write  # IMPORTANT: mandatory for trusted publishing
+#     permissions:
+#       id-token: write  # IMPORTANT: mandatory for trusted publishing
 
-    steps:
-    - name: Download all the dists
-      uses: actions/download-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
-    - name: Publish distribution 📦 to TestPyPI
-      uses: pypa/gh-action-pypi-publish@release/v1
-      with:
-        repository-url: https://test.pypi.org/legacy/
+#     steps:
+#     - name: Download all the dists
+#       uses: actions/download-artifact@v4
+#       with:
+#         name: python-package-distributions
+#         path: dist/
+#     - name: Publish distribution 📦 to TestPyPI
+#       uses: pypa/gh-action-pypi-publish@release/v1
+#       with:
+#         repository-url: https://test.pypi.org/legacy/
 
-  build-and-push-dockerhub:
-    runs-on: ubuntu-24.04
-    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
-    needs:
-    - publish-to-pypi
+#   build-and-push-dockerhub:
+#     runs-on: ubuntu-24.04
+#     if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
+#     needs:
+#     - publish-to-pypi
 
-    # No 'packages: write' needed, but 'contents: read' is still required for checkout
-    permissions:
-      contents: read 
+#     # No 'packages: write' needed, but 'contents: read' is still required for checkout
+#     permissions:
+#       contents: read 
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
 
-      - name: Extract Python Package Version
-        id: get_version
-        # 1. Install the required TOML parser (must be first)
-        run: pip install toml
+#       - name: Extract Python Package Version
+#         id: get_version
+#         # 1. Install the required TOML parser (must be first)
+#         run: pip install toml
 
-      - name: Extract Python Package Version
-        run: |
-          VERSION=$(python -c "
-import toml
-data = toml.load('pyproject.toml')
-# Assuming version is defined under [tool.poetry]
-version = data['tool']['poetry']['version']
-print(version)
-" 2>/dev/null)
+#       - name: Extract Python Package Version
+#         run: |
+#           VERSION=$(python -c "
+# import toml
+# data = toml.load('pyproject.toml')
+# # Assuming version is defined under [tool.poetry]
+# version = data['tool']['poetry']['version']
+# print(version)
+# " 2>/dev/null)
           
-          if [ -z "$VERSION" ]; then
-            echo "::error::Could not find 'version' in pyproject.toml. Check the path used in the Python script."
-            exit 1
-          fi
+#           if [ -z "$VERSION" ]; then
+#             echo "::error::Could not find 'version' in pyproject.toml. Check the path used in the Python script."
+#             exit 1
+#           fi
 
-          echo "PYTHON_VERSION=$VERSION" >> $GITHUB_ENV
-          echo "::notice file=pyproject.toml::Extracted version: $VERSION"
+#           echo "PYTHON_VERSION=$VERSION" >> $GITHUB_ENV
+#           echo "::notice file=pyproject.toml::Extracted version: $VERSION"
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+#       - name: Set up QEMU
+#         uses: docker/setup-qemu-action@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          registry: docker.io 
-          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
-          password: ${{ secrets.DOCKER_HUB_TOKEN }} 
+#       - name: Log in to Docker Hub
+#         uses: docker/login-action@v3
+#         with:
+#           registry: docker.io 
+#           username: ${{ secrets.DOCKER_HUB_USERNAME }} 
+#           password: ${{ secrets.DOCKER_HUB_TOKEN }} 
 
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: kalavai/${{ github.event.repository.name }}
-          tags: |
-            # Tag 1: The Pypi version (e.g., 0.8.0)
-            type=raw,value=${{ env.PYTHON_VERSION }}
-            # Tag 2: 'latest' (only on the default branch)
-            type=raw,value=latest,enable={{is_default_branch}}
+#       - name: Extract metadata (tags, labels) for Docker
+#         id: meta
+#         uses: docker/metadata-action@v5
+#         with:
+#           images: kalavai/${{ github.event.repository.name }}
+#           tags: |
+#             # Tag 1: The Pypi version (e.g., 0.8.0)
+#             type=raw,value=${{ env.PYTHON_VERSION }}
+#             # Tag 2: 'latest' (only on the default branch)
+#             type=raw,value=latest,enable={{is_default_branch}}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+#       - name: Build and push Docker image
+#         uses: docker/build-push-action@v5
+#         with:
+#           context: .
+#           push: true
+#           tags: ${{ steps.meta.outputs.tags }}
+#           labels: ${{ steps.meta.outputs.labels }}
+#           cache-from: type=gha
+#           cache-to: type=gha,mode=max
